name: material_snackbar
description: A flutter plugin for displaying snackbars with the newest material design on desktop and mobile.
version: 2.1.0
repository: https://github.com/RoundedInfinity/material_snackbar

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  animations: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
