name: material_snackbar
description: A flutter plugin for displaying snackbars with the newest material design on desktop and mobile.
version: 2.0.0
repository: https://github.com/RoundedInfinity/material_snackbar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  animations: ^2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.roundedinfinity.material_snackbar
        pluginClass: MaterialSnackbarPlugin
      ios:
        pluginClass: MaterialSnackbarPlugin
      macos:
        pluginClass: MaterialSnackbarPlugin
      windows:
        pluginClass: MaterialSnackbarPlugin
      web:
        pluginClass: MaterialSnackbarWeb
        fileName: material_snackbar_web.dart
